In [1]:
#Import

import pandas as pd
from sqlalchemy import create_engine

In [6]:
#Load
database_filepath = "../data/Disaster-Messages-Categories.db"
engine = create_engine('sqlite:///'+database_filepath)
df=pd.read_sql_table('DisasterTable',engine).set_index('id')

In [13]:
y=df.message
X=df.drop(['message','original'], axis=1)

In [15]:
pd.get_dummies(X, columns=['genre'])

,related,request,offer,aid_related,medical_help,medical_products,search_and_rescue,security,military,child_alone,...,floods,storm,fire,earthquake,cold,other_weather,direct_report,genre_direct,genre_news,genre_social
id,,,,,,,,,,,,,,,,,,,,,
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7,1,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
8,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9,1,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
12,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30261,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
30262,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
30263,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
30264,1,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
30265,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [12]:
y

,genre,related,request,offer,aid_related,medical_help,medical_products,search_and_rescue,security,military,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
id,,,,,,,,,,,,,,,,,,,,,
2,direct,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,direct,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
8,direct,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,direct,1,1,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,direct,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30261,news,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30262,news,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30263,news,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30264,news,1,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
30265,news,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0